spring.application.name=demo-Electricity-App
server.port=8090

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/multitenantpowerdb
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

#Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#Mail Invitation
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vinoothnamukkamala@gmail.com
spring.mail.password=gxqx bbzu dgzt oncx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Multi Tenant Configuration
spring.jpa.properties.hibernate.multiTenancy=SCHEMA

# Enable Flyway migrations
spring.flyway.enabled=true
# Create a baseline entry when migrating a non-empty database
spring.flyway.baseline-on-migrate=true
# Set the custom directory for your SQL migration files
spring.flyway.locations=classpath:db/migration/master
# Change the name of Flyway's metadata tracking table
spring.flyway.table=flyway-schema-history
# Validate migrations against applied history during application startup
spring.flyway.validate-on-migration=true


logging.level.org.hibernate.SQL=DEBUG
