spring.application.name=demo-Electricity-App

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/PowerDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Multi Tenant Configuration
spring.jpa.properties.hibernate.multiTenancy=SCHEMA

# Flyway
spring.flyway.enabled=false

logging.level.org.hibernate.SQL=DEBUG
